# Generated by Django 5.1.4 on 2025-02-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='coins',
            field=models.IntegerField(default=5),
        ),
    ]
