# Generated by Django 5.1.4 on 2025-02-08 06:43

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_question_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='module',
            new_name='categorie',
        ),
        migrations.AddField(
            model_name='meet',
            name='membersInAgenda',
            field=models.ManyToManyField(blank=True, related_name='added_to_their_agendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meet',
            name='nbJoined',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meet',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meet',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meet',
            name='titre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meet',
            name='niveau',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
